[tools]
bat = "latest"
bottom = "latest"
cargo-binstall = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
delta = "latest"
#"cargo:dotter" = "latest"
dotnet = "10"
duf = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
node = "latest"
python = "latest"
ripgrep = "latest"
ruby = "3"
ruff = "latest"
rust = "latest"
"cargo:sheldon" = "latest"
starship = "latest"
"cargo:tre-command" = "latest" 
usage = "latest"
uv = "latest"
xh = "latest"
zoxide = "latest"
