[tools]
usage = "latest"
xh = "latest"
ruby = "latest"
"npm:@sourcegraph/amp" = "latest"
"npm:@kilocode/cli" = "latest"
"npm:clawdbot" = "latest"
"npm:@musistudio/claude-code-router" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
